version: '3'

services:
  tweet-api:
    container_name: tweet-api
    build: ./
    environment:
      - APP_NAME=tweet-api:dev
      - NEW_RELIC_LICENSE_KEY=6044c7173b704a4b1a43758e323137eb17c3NRAL
      - TWITTER_CONSUMER_KEY=bABFAhZIn065zApAAOQXzKkCV
      - TWITTER_CONSUMER_SECRET=gQKdByOS5a8K15MJX2xwI4NFsqP6rrxaNU6EZkB0jfdXRdeykJ
      - TWITTER_ACCESS_TOKEN_KEY=362833614-LLGxAhx8badCCtwSrrld21cpVN5nEG0UfM7vlcwM
      - TWITTER_ACCESS_TOKEN_KEY=v5XUfML1HnLOaFwh1OdxK6rvBBgy8WUpCXsEvK140kSUj
    restart: unless-stopped
    volumes:
      - ./src/var/log:/app/src/var/log/
    networks:
      - bubble
    ports:
      - "8081:8080"

  mongo:
    container_name: mongo
    image: mongo:4
    volumes:
      - mongo-dictionary:/data/db:delegated
    networks:
      - bubble
    ports:
      - "27017:27017"

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - bubble
    ports:
      - 9200:9200
      - 9300:9300
  gssidecar:
    image: markusgulden/graylog2-sidecar-docker
    environment:
      - GS_SERVER_URL=http://graylog:9000/api/
      - GS_NODE_ID=10f74138
      - GS_TAGS=['tweet']
      - GS_LIST_LOG_FILES=['/var/log/']
      - GS_TLS_SKIP_VERIFY=true
      - GS_SERVER_API_TOKEN=1cu59lgh604dfasthuhum2pmvd5naq2l0ls6ah234gmbj45j7v1d
    volumes:
      - ./src/var/log:/var/log/
      - ./src/var/log:/var/lib/graylog-sidecar/collectors/filebeat/log
    depends_on:
      - mongo
      - elasticsearch
      - graylog
    networks:
      - bubble
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.2
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    networks:
      - bubble
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
networks:
  bubble:
    driver: bridge
networks:
  bubble:
    external: true
volumes:
  mongo-dictionary:
